#!/bin/bash
#
# kasutajate lisamise skript

if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
else
	failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "fail on korras"
    for rida in $(cat $failinimi)
    do
	nimi=$(echo $rida | cut -f1 -d:)
      # sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja nüüd echo asemel tuleb kutsuda vajalik skript
      # echo $rida
	sh lisa_kasutaja $nimi # sellega me laseme lisa_kasutaja skript tööle
	chpasswd < $failinimi
done

  else
    echo "probleem failiga $failinimi"
  fi
fi
